version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    container_name: echo-backend
    
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: echo-frontend